"use client";
import { FormEvent, useMemo, useState } from "react";
const services=[["01","Коктейльный бар","Авторская карта, бармены, лёд, стекло и вся логистика."],["02","Кофейная станция","Эспрессо-бар с бариста для деловых и дневных событий."],["03","Бармен-шоу","Флейринг, огонь и интерактив — когда бар становится частью программы."],["04","Бар под концепцию","Меню, форма команды и оформление, подобранные под ваш сценарий."]];
const cases=[["Свадьба","Камерный ужин на 48 гостей","4 часа · 192 коктейля"],["Корпоратив","Запуск нового продукта","180 гостей · 2 стойки"],["Частный вечер","День рождения на крыше","60 гостей · авторское меню"]];
export default function Home(){const[guests,setGuests]=useState(50);const[hours,setHours]=useState(4);const[format,setFormat]=useState("Коктейльный бар");const[show,setShow]=useState(false);const[sent,setSent]=useState(false);const drinks=guests*4;const total=drinks*(format==="Кофейная станция"?300:450)+hours*3000+(drinks>200?9000:0);const range=useMemo(()=>`${Math.round(total/1000)} 000–${Math.round(total*1.15/1000)} 000 ₽`,[total]);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSent(true)};return <main>
<header className="nav"><a href="#top" className="brand">BAR<span>PRO</span></a><nav><a href="#services">Форматы</a><a href="#calculator">Калькулятор</a><a href="#cases">Кейсы</a><a href="#contacts">Контакты</a></nav><button className="small-button" onClick={()=>setShow(true)}>Рассчитать</button></header>
<section id="top" className="hero"><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">Москва · область · любое пространство</p><h1>Бар, о котором<br/><em>говорят</em> после вечера</h1><p className="hero-text">Выездной бар и барный кейтеринг под ключ: сильная команда, точный сервис и коктейли, которые становятся частью события.</p><div className="hero-actions"><button className="gold-button" onClick={()=>setShow(true)}>Рассчитать событие</button><a className="text-link" href="#services">Смотреть форматы <b>↘</b></a></div></div><div className="hero-stats"><div><b>11+</b><span>лет в HoReCa</span></div><div><b>500+</b><span>событий</span></div><div><b>24/7</b><span>на связи</span></div></div></section>
<section id="services" className="section services"><div className="section-intro"><p className="eyebrow">Форматы</p><h2>Не просто налить.<br/>Создать <em>впечатление.</em></h2></div><div className="service-grid">{services.map(([n,t,d])=><article className="service-card" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><a href="#calculator">Собрать формат <b>↗</b></a></article>)}</div></section>
<section id="calculator" className="section calculator"><div className="calc-copy"><p className="eyebrow">Предварительный расчёт</p><h2>Понятный бюджет<br/>за <em>две минуты.</em></h2><p>Соберите ориентир до разговора с менеджером. В финальной смете учтём площадку, сценарий, меню и детали вашего вечера.</p><ul><li>Команда, инвентарь и расходники</li><li>Меню и расчёт напитков на гостя</li><li>Монтаж, демонтаж и логистика по Москве</li></ul></div><div className="calculator-card"><div className="choice-row"><button className={format==="Коктейльный бар"?"selected":""} onClick={()=>setFormat("Коктейльный бар")}>Коктейльный</button><button className={format==="Кофейная станция"?"selected":""} onClick={()=>setFormat("Кофейная станция")}>Кофейный</button></div><label>Гостей <strong>{guests}</strong><input type="range" min="20" max="300" step="10" value={guests} onChange={e=>setGuests(Number(e.target.value))}/><small>20 <span>160</span> 300</small></label><label>Часов работы <strong>{hours} ч</strong><input type="range" min="3" max="10" value={hours} onChange={e=>setHours(Number(e.target.value))}/><small>3 ч <span>6 ч</span> 10 ч</small></label><div className="estimate"><span>Ориентировочная стоимость</span><b>{range}</b><p>{guests} гостей · {hours} ч · {drinks} напитков · {drinks>200?"2 бармена":"1 бармен"}</p></div><button className="gold-button full" onClick={()=>setShow(true)}>Получить точную смету</button></div></section>
<section id="cases" className="section cases"><div className="section-intro"><p className="eyebrow">Реальные сценарии</p><h2>Каждый вечер —<br/>со своим <em>характером.</em></h2></div><div className="case-grid">{cases.map(([t,h,i],n)=><article className={`case case-${n+1}`} key={h}><div><span>{t}</span><h3>{h}</h3><p>{i}</p></div></article>)}</div></section>
<section className="quote"><p>«Лучший бар на событии — тот, который выглядит естественной частью праздника, а не отдельной услугой.»</p><span>Команда BarPro</span></section>
<section className="section faq"><p className="eyebrow">Без сюрпризов</p><h2>Вопросы, которые<br/>обычно задают <em>до брони.</em></h2><details open><summary>Что входит в выездной бар под ключ?<b>+</b></summary><p>Стойка, стекло и инвентарь, лёд, ингредиенты, работа команды и логистика. Состав зависит от выбранного формата.</p></details><details><summary>За сколько времени лучше бронировать дату?<b>+</b></summary><p>Чем раньше, тем больше свободы в выборе команды и концепции.</p></details><details><summary>Можно ли сделать безалкогольную карту?<b>+</b></summary><p>Да. Соберём полноценное меню из авторских безалкогольных коктейлей, лимонадов или кофе.</p></details></section>
<footer id="contacts"><div><a href="#top" className="brand">BAR<span>PRO</span></a><p>Выездной бар и барный кейтеринг<br/>для событий в Москве и области.</p></div><div><p className="eyebrow">Связаться</p><a className="contact-link" href="mailto:hello@barpro-event.ru">hello@barpro-event.ru</a><button className="gold-button" onClick={()=>setShow(true)}>Оставить заявку</button></div><small>Демо-версия. Контакты и финальные цены будут заменены на ваши перед запуском.</small></footer>
{show&&<div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal"><button className="close" onClick={()=>{setShow(false);setSent(false)}}>×</button>{sent?<div className="success"><p className="eyebrow">Спасибо</p><h2>Расчёт<br/><em>почти готов.</em></h2><p>В рабочей версии форма будет отправлять бриф менеджеру. Сейчас это демонстрация механики заявки.</p><button className="gold-button" onClick={()=>setShow(false)}>Вернуться к сайту</button></div>:<form onSubmit={submit}><p className="eyebrow">Заявка на расчёт</p><h2>Расскажите<br/>о вашем <em>событии.</em></h2><label>Имя<input required placeholder="Как к вам обращаться"/></label><label>Телефон<input required type="tel" placeholder="+7 (___) ___-__-__"/></label><label>Формат<select defaultValue={format}><option>Коктейльный бар</option><option>Кофейная станция</option><option>Бармен-шоу</option><option>Нужна консультация</option></select></label><button className="gold-button full">Получить расчёт</button><small>Нажимая кнопку, вы соглашаетесь на обработку данных.</small></form>}</div></div>}</main>}
